pipeline {
    agent any

    tools {
        maven "M2_HOME"
        jdk "JAVA_HOME"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', 
                    url: 'https://github.com/louiswin03/devops2.git'
            }
        }

        stage('Build') {
            steps {
                // On ajoute dir('nom-du-dossier') pour entrer dedans
                dir('student-management') {
                    sh "mvn clean package -Dmaven.test.skip=true"
                }
            }
        }
    }
}
